#ifndef DEFINE_HPP
# define DEFINE_HPP

#define DEFAULT_GRAPH_POINT '.'
#define DEFAULT_GRAPH_X_AXIS '-'
#define DEFAULT_GRAPH_Y_AXIS '|'
#define DEFAULT_GRAPH_ZERO '+'
#define DEFAULT_GRAPH_VECTOR 'x'

#define DEFAULT_ADDITIONAL_SPACE_Y 2
#define DEFAULT_ADDITIONAL_SPACE_X 1

#define XLABEL 4
#define YLABEL 8

#define ERROR_LABEL_SIZE_LIMIT 1000
#define BASIC_GAP 5.0f
#define BASIC_ADJUST_VALUE 3.0f

#define MINIMUM_LABEL_RPINTWIDTH 2

#endif //DEFINE_HPP